DROP TABLE IF EXISTS COVERT;

CREATE TABLE COVERT(

covert_id INT AUTO_INCREMENT PRIMARY KEY,
covert_name VARCHAR(150) NOT NULL,
covert_type VARCHAR(150) NOT NULL,
covert_timestamp VARCHAR(150) NOT NULL
);
 



